-- The table SEG-10 needs and Phase 2 deliberately did not create
-- (02-02-SUMMARY.md): Phase 2 shipped only the static `agent_action_catalog`
-- (three seeded rows) and the `audit_log` shell; the engine, the queue and
-- the UI were all explicitly deferred to Phase 4. Hand-authored — the RLS
-- half cannot be generated by `drizzle-kit generate`, and mixing generated
-- and hand-written halves has already caused journal drift in this repo
-- (same reason 0001/0006/0013/0014/0015 give in their own headers).
--
-- `risk_level` is a SNAPSHOT copied at proposal time, not a live join to
-- `agent_action_catalog.risk_level` — a later re-classification of an action
-- type must not rewrite the meaning of history already sitting in the queue.
--
-- LD-09 (locked decision): high-risk actions are NOT executed by a suspended
-- Inngest function waiting on an event. The turn that proposes them finishes
-- immediately, and a separate function (plan 04-09) executes the action when
-- a human decides. That is why this table carries everything needed to
-- replay the tool call later — `tool_name`, `tool_input`, `client_id`,
-- `conversation_phone_number`, `channel` — not just a reference to a live
-- run that may no longer exist by the time a human responds.
--
-- LD-04 (locked decision, do not revisit): the two human-facing policies
-- below get NO `client_contact` branch at all — a client contact must never
-- learn that an action about them is awaiting internal approval. This is the
-- same deliberate divergence 0014's header documents for `audit_log`; a
-- `client_contact` scope simply matches neither OR branch and reads zero
-- rows. Do not "fix" this for consistency with `clients` (0007) — that would
-- reintroduce the exact leak this table exists to avoid.
--
-- LD-03 (locked decision, do not revisit): `client_id IS NULL` rows
-- (agency-internal actions) are visible to every team member, admin and
-- member alike, inside the member branch below — same product default as
-- `audit_log`/`messages` (0014/0015).
--
-- Mandatory GUC rule (0002/0007): every uuid GUC comparison below uses
-- `NULLIF(current_setting('app.xxx', true), '')::uuid`, never a bare
-- `::uuid` cast — a pooled connection reused across requests returns `''`,
-- not `NULL`, for a transaction-local GUC after its first use on that
-- physical backend, and `''::uuid` throws instead of failing closed.

CREATE TABLE "approval_queue" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"agency_id" text NOT NULL,
	"client_id" uuid,
	"action_type_code" text NOT NULL,
	"risk_level" text NOT NULL,
	"tool_name" text NOT NULL,
	"tool_use_id" text NOT NULL,
	"tool_input" jsonb NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"summary" text NOT NULL,
	"requested_by_identity_type" text NOT NULL,
	"requested_by_identity_id" uuid,
	"channel" text DEFAULT 'whatsapp' NOT NULL,
	"conversation_phone_number" text,
	"decided_by_team_member_id" uuid,
	"decided_at" timestamp with time zone,
	"execution_result" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "approval_queue_risk_level_check" CHECK ("approval_queue"."risk_level" in ('low', 'high')),
	CONSTRAINT "approval_queue_status_check" CHECK ("approval_queue"."status" in ('pending', 'approved', 'rejected', 'executed', 'failed')),
	CONSTRAINT "approval_queue_requested_by_identity_type_check" CHECK ("approval_queue"."requested_by_identity_type" in ('team_member', 'client_contact', 'unknown')),
	CONSTRAINT "approval_queue_channel_check" CHECK ("approval_queue"."channel" in ('whatsapp', 'web'))
);
--> statement-breakpoint

ALTER TABLE "approval_queue" ADD CONSTRAINT "approval_queue_agency_id_agencies_id_fk" FOREIGN KEY ("agency_id") REFERENCES "public"."agencies"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint

ALTER TABLE "approval_queue" ADD CONSTRAINT "approval_queue_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint

ALTER TABLE "approval_queue" ADD CONSTRAINT "approval_queue_action_type_code_agent_action_catalog_code_fk" FOREIGN KEY ("action_type_code") REFERENCES "public"."agent_action_catalog"("code") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint

ALTER TABLE "approval_queue" ADD CONSTRAINT "approval_queue_decided_by_team_member_id_team_members_id_fk" FOREIGN KEY ("decided_by_team_member_id") REFERENCES "public"."team_members"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint

CREATE UNIQUE INDEX "approval_queue_agency_id_tool_use_id_idx" ON "approval_queue" USING btree ("agency_id","tool_use_id");
--> statement-breakpoint

-- === audit_log shape gap (SEG-10/SEG-11) ===
-- The bitácora has to distinguish "the agent did this" from "the agent
-- proposed this and is waiting" from "the team said no"; before this
-- migration `audit_log` had no column that could carry that.

ALTER TABLE "audit_log" ADD COLUMN "status" text DEFAULT 'executed' NOT NULL;
--> statement-breakpoint

ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_status_check" CHECK ("audit_log"."status" in ('executed', 'pending_approval', 'approved_executed', 'rejected', 'failed'));
--> statement-breakpoint

ALTER TABLE "audit_log" ADD COLUMN "approval_id" uuid;
--> statement-breakpoint

ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_approval_id_approval_queue_id_fk" FOREIGN KEY ("approval_id") REFERENCES "public"."approval_queue"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint

-- === GRANTs ===
-- GRANT and RLS are independent layers (0001_rls_policies.sql lines 54-56).
-- No DELETE grant: a decided item is history, and agency deletion removes
-- rows via the FK cascade, which is not subject to RLS — same reasoning as
-- 0013's `messages` GRANT.

GRANT SELECT, INSERT, UPDATE ON approval_queue TO app_user;
--> statement-breakpoint

ALTER TABLE approval_queue ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE approval_queue FORCE ROW LEVEL SECURITY;
--> statement-breakpoint

-- The system actor: the agent proposing a high-risk action, and later plan
-- 04-09's replay function reading/updating the row. FOR ALL so that
-- INSERT ... RETURNING and UPDATE ... WHERE both work: Postgres applies
-- SELECT policies to a RETURNING clause and to an UPDATE's row lookup, so a
-- write-only policy would silently break the idempotency gate (which reads
-- back the inserted id) and the replay function's own status update. Same
-- rationale 0013 gives for messages_system_webhook_all.
CREATE POLICY approval_queue_system_all ON approval_queue
  FOR ALL
  USING (
    agency_id = current_setting('app.agency_id', true)
    AND coalesce(current_setting('app.actor', true), '') = 'system_webhook'
  )
  WITH CHECK (
    agency_id = current_setting('app.agency_id', true)
    AND coalesce(current_setting('app.actor', true), '') = 'system_webhook'
  );
--> statement-breakpoint

-- Human read policy (LD-04, see header). Admin sees everything; member sees
-- team-internal (client_id IS NULL) rows plus their assigned clients via
-- client_assignments. Any other scope matches neither branch and reads zero
-- rows.
CREATE POLICY approval_queue_select_by_role ON approval_queue
  FOR SELECT
  USING (
    agency_id = current_setting('app.agency_id', true)
    AND (
      coalesce(current_setting('app.role', true), '') = 'admin'
      OR (
        coalesce(current_setting('app.role', true), '') = 'member'
        AND (
          client_id IS NULL
          OR client_id IN (
            SELECT client_id FROM client_assignments
            WHERE team_member_id = NULLIF(current_setting('app.team_member_id', true), '')::uuid
          )
        )
      )
    )
  );
--> statement-breakpoint

-- Human decision policy — the exact same visibility predicate as the SELECT
-- policy above, UPDATE only, so visibility and decision rights cannot drift
-- apart (T-04-12). RLS cannot restrict WHICH columns change, so the Server
-- Action in plan 04-09 is what constrains the update to
-- status/decided_by_team_member_id/decided_at and to rows currently
-- status = 'pending' (T-04-13). RLS's job here is only "may this human see
-- and touch this row at all".
CREATE POLICY approval_queue_decide_by_role ON approval_queue
  FOR UPDATE
  USING (
    agency_id = current_setting('app.agency_id', true)
    AND (
      coalesce(current_setting('app.role', true), '') = 'admin'
      OR (
        coalesce(current_setting('app.role', true), '') = 'member'
        AND (
          client_id IS NULL
          OR client_id IN (
            SELECT client_id FROM client_assignments
            WHERE team_member_id = NULLIF(current_setting('app.team_member_id', true), '')::uuid
          )
        )
      )
    )
  )
  WITH CHECK (
    agency_id = current_setting('app.agency_id', true)
    AND (
      coalesce(current_setting('app.role', true), '') = 'admin'
      OR (
        coalesce(current_setting('app.role', true), '') = 'member'
        AND (
          client_id IS NULL
          OR client_id IN (
            SELECT client_id FROM client_assignments
            WHERE team_member_id = NULLIF(current_setting('app.team_member_id', true), '')::uuid
          )
        )
      )
    )
  );
